cuda:
  devices: '0' # or comma separated list of device ids e.g. '0,3'

data: "ruthchy/semantic-length-generalization-logo-data-desc-ascii_35"

input:
  include_ascii: True
  include_desc: True

model:
  name: "codellama/CodeLlama-7b-Instruct-hf" 
  # xu3kev/deepseekcoder-7b-logo-pbe
training:
  trainer_output_only: False
  # pre-processing
  max_seq_length: 2048
  # training
  learning_rate: 2e-4 # 2e-4, 1e-4, 5e-5, 2e-5 recommended 2e-04=2e-4 in PBE paper (smaller lr slows learning down potentially higher accuracy)
  warmup_steps: 20 # 20, 100, 500, 1000 recommended 20 in PBE paper
  lr_scheduler_type: "cosine" # "linear" (default), "cosine", "cosine_with_restarts", "polynomial", "constant", "constant_with_warmup" # linear and cosine are usually; used cosine is used in PBE
  train_epochs: 1
  per_device_batch_size: 32 # PBE 64 
  gradient_accumulation_steps: 4
  # checkpointing and evaluation
  save_steps: 10
  eval_steps: 1
  logging_steps: 1
  # reproducibility
  random_seed: 42

lora:
  rank: 8 # 8, 16, 32, 64, 128 (recommended) 512 in PBE paper 
  alpha: 32 #512
# the higher the rank and alpha, the more expressive the model can cause offerfitting