cuda:
  devices: '2' # or comma separated list of device ids e.g. '0,3'

data: "ruthchy/semantic-length-generalization-logo-data-desc-ascii_35"

model:
  name: "codellama/CodeLlama-7b-hf" 
  # xu3kev/deepseekcoder-7b-logo-pbe
training:
  trainer_output_only: False
  # pre-processing
  max_seq_length: 2048
  # training
  learning_rate: 2e-4 # 2e-4, 1e-4, 5e-5, 2e-5 recommended 2e-04=2e-4 in PBE paper (smaller lr slows learning down potentially higher accuracy)
  train_epochs: 1
  per_device_batch_size: 64
  gradient_accumulation_steps: 4
  warmup_steps: 20 # is set in TrainArguments()/SFTConfig()
  # checkpointing and evaluation
  save_steps: 100
  eval_steps: 100
  logging_steps: 1
  # reproducibility
  random_seed: 42

lora:
  rank: 8 # 8, 16, 32, 64, 128 (recommended) 512 in PBE paper 
  alpha: 32 #512
# the higher the rank and alpha, the more expressive the model can cause offerfitting

#lr_scheduler_type - Cosine is potentially superior and i think PBE used it have to check where the parameter is set

