_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 84
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 84
                - 98
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.19.4
            "6": 4.46.3
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
learning_rate:
    value: 5e-05
max_seq_length:
    value: 2048
num_epochs:
    value: 3
num_train_epochs:
    value: 3
